apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: demoapp
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
   - port: 8080
     nodePort: 31514
